### PR TITLE
DefaultUncaughtExceptionHandler 

### PR DESCRIPTION
**Pull request by ghost**
- DefaultUncaughtExceptionHandler 
- Removed some Deprecated Functions
- moved some code to VM

### CODE REVIEW

**Comment by marpme** [comment]
You should `.gitignore` all the gradle/idea files

**Comment by 2lazy2debug** [comment]
@SEVCO thank you for your work. I'm finishing working on the Locale settings in-app, once done I'm gonna look at that def 
@marpme thanks for the review request, would've missed that PR for at least another month.

**Comment by ghost** [comment]
Thanks i'll fix some code. Let me know if you need some help on another feature.

**Comment by ghost** [comment]
Im replacing PreferencesManager.getInstance() with a static  PREFERENCES_MANAGER cause it's a singleton

**Comment by 2lazy2debug** [comment]
@SEVCO have you tested your changes of the PreferencesManager? The static value you declared is a call to the init() method that will throw an AssertionError if the instance already exists, generally you would've called the getInstance() method (after that the init() function is called a first time). 

I'm  ok with using static imports tho (you lose a bit on readability IMO but it's a matter of taste)  but at this point I'd declare them at the method level so that the scope of the singleton is limited to the use in the related class 

I.e. Instead of  :
```java
import static vergecurrency.vergewallet.wallet.VergeWalletApplication.PREFERENCES_MANAGER;
//...
String[] mnemonic = MnemonicManager.getMnemonicFromJSON(PREFERENCES_MANAGER.getMnemonic());
```

use 

```java
import static vergecurrency.vergewallet.wallet.VergeWalletApplication.PREFERENCES_MANAGER.getMnemonic;
//...
String[] mnemonic = MnemonicManager.getMnemonicFromJSON(getMnemonic());
```
If we choose to use this pattern, it might be worth using it for the xxxUtils classes that are all static, just to keep consistency with the code.

**Comment by ghost** [comment]
getInstance() throws an exception either. In this case my UnhandledExceptionHandler will handle the exception. Because of this behaviour i would prefer the static utils option.

I agree with your suggestion

**Comment by 2lazy2debug** [comment]
getInstance() will thrown an exception because init()  hasn't been called. But after that it won't. your method will just throw an exception on a second call. 

I'm moving the init() method to an App class that extends Application (not sure if I pushed yet), so that your static change will work, then I think it's ready to merge :)  - we'll polish this static import matter in a second time (unless you want to do this now of course). 

About the features request, well, I don't really have anything at the moment besides the open issues, but I'll agree that they're boring :) I'd wait that the bitcore implementation is done and I'll work on creating a coherent issue list for the missing features.

I'd like also to make sure you know I deeply appreciate the time you're investing and the solutions you're proposing and am always happy to see people contributing, hit me up on discord or Telegram if you want to discuss further stuff.

**Comment by ghost** [comment]
I already created an App class extending Application. VergeWalletApplication.class

I will polish the static stuff this week

Its a pleasure and an honor to contribute :)

**Review by 2lazy2debug — APPROVED** [review]

**Comment by 2lazy2debug** [comment]
Hey, 

I'm working on the merge right now, I will possibly finish tomorrow since I'm out of time. I just noticed that you update the UI straight from the ViewModels.

Please don't in the future, the ViewModels should never directly communicate with the UI and they should work with 0 knowledge of the Android environment. 

On the other hand, I saw the Application extended class, I'll use yours and wipe mine :)

**Comment by ghost** [comment]
Ok thanks for your feedback.
There are some issues i need to fix. Could you please wait for another update until you will merge this pull request? Im sorry

**Comment by 2lazy2debug** [comment]
Ok, since you're fxing some stuff, please revert the changes on the Paperkey ViewModels and then squash the commits :)

**Comment by SEVCO** [comment]
https://vws2.swenvanzanten.com/price/api/v1/price/USD

HOW ????
https://vws2

**Comment by ghost** [comment]
ready :)

**Comment by 2lazy2debug** [comment]
Merged, thanks for your contribution :) Hit me up on discord or telegram if you have the occasion, it'll be easier to discuss things 

TG : @CabrasManuel 
Discord : @2lazy2java#2774

**Pull request merged**
